In [85]:
import numpy as np

In [86]:
# This is a neuron with x as input, w as weights and a bias value
x = [1,2,3]
w = [0.2,0.8,-0.5]
bias = 2

In [87]:
output = np.dot(x,w) + bias
print(output)

2.3


In [88]:
i = [1,2,3,2.5]
w_new = [0.2,0.8,-0.5,1]
bias_new = 2
o = np.dot(i,w_new) + bias_new
print(o)

4.8


Now lets code a layer of 3 neurons with four inputs

In [89]:
inputs = np.array([1,2,3,2.5])

weights = np.array([[0.2,0.8,-0.5,1],
           [0.5,-0.910,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]])
bias = np.array([2,3,0.5]).reshape(-1,1)

In [90]:
inputs = np.append(inputs,1)

In [91]:
inputs = inputs.reshape(5,1)


In [92]:
weights = np.hstack((weights,bias))

In [93]:
weights

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ,  2.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ,  3.  ],
       [-0.26, -0.27,  0.17,  0.87,  0.5 ]])

In [94]:
inputs

array([[1. ],
       [2. ],
       [3. ],
       [2.5],
       [1. ]])

In [95]:
out = weights@inputs

In [100]:
out

array([[4.8  ],
       [1.21 ],
       [2.385]])

In [101]:
i1 = [[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.910,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
bias = [2,3,0.5]


In [102]:
output = np.dot(i1,np.array(weights).T) + bias
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [104]:
i1 = [[1,2,3,2.5],
      [2,5,-1,2],
      [-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.910,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
bias = [2,3,0.5]

weights2 = [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]
bias2 = [-1,2,-0.5]

i1 = np.array(i1)
weights = np.array(weights)
weights2 = np.array(weights2)
bias = np.array(bias)
bias2 = np.array(bias2)

# Output of layer 1
f1 = np.dot(i1,weights.T) + bias
# Output f layer 2 
f2 = np.dot(f1,weights2.T) + bias2
print(f2)



[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
